[package]
authors = ["marcograss"]
categories = ["command-line-utilities", "compression", "encoding", "parsing", "parser-implementations"]
default-run = "partialzip"
description = "Download single files from online zip archives or list the content"
documentation = "https://docs.rs/partialzip"
edition = "2021"
exclude = ["/testdata", "/.cargo"]
homepage = "https://github.com/marcograss/partialzip"
keywords = ["network", "utility", "io", "tool", "library"]
license = "MPL-2.0"
name = "partialzip"
readme = "README.md"
repository = "https://github.com/marcograss/partialzip"
rust-version = "1.70.0"
version = "2.1.2"

[features]
cmdline = ["dep:anyhow", "dep:clap", "dep:env_logger"]
default = ["cmdline", "progressbar"]
progressbar = ["dep:indicatif"]

[lib]
path = "src/lib.rs"

[[bin]]
name = "partialzip"
path = "src/bin/partialzip.rs"
required-features = ["cmdline"]

[[bench]]
harness = false
name = "pz_benchmark"

[dependencies]
anyhow = {version = "1.0.75", optional = true}
bytesize = "1.3.0"
clap = {version = "4.4.5", optional = true}
conv = "0.3.3"
curl = "0.4.44"
env_logger = {version = "0.10.0", optional = true}
indicatif = {version = "0.17.7", optional = true}
log = "0.4.20"
num-traits = "0.2.16"
thiserror = "1.0.49"
url = "2.4.1"
zip = {version = "0.6.6", default-features = false, features = ["bzip2", "deflate", "zstd"] }

[dev-dependencies]
actix-files = "0.6.2"
actix-web = {version = "4.4.0", default-features = false, features = []}
anyhow = "1.0.75"
assert_cmd = "2.0.12"
criterion = "0.5.1"
predicates = "3.0.4"
tempfile = "3.8.0"
tokio = {version = "1.32.0", features = ["macros", "rt-multi-thread"]}
