[package]
authors = ["marcograss"]
categories = ["command-line-utilities", "compression", "encoding", "parsing", "parser-implementations"]
default-run = "partialzip"
description = "Download single files from online zip archives"
documentation = "https://docs.rs/partialzip"
edition = "2021"
exclude = ["/testdata", "/.cargo"]
homepage = "https://github.com/marcograss/partialzip"
keywords = ["network", "utility", "io", "tool", "library"]
license = "MPL-2.0"
name = "partialzip"
readme = "README.md"
repository = "https://github.com/marcograss/partialzip"
rust-version = "1.64.0"
version = "2.0.0-alpha.1"

[features]
cmdline = ["dep:anyhow", "dep:clap", "dep:env_logger"]
default = ["cmdline", "progressbar"]
progressbar = ["dep:indicatif"]

[lib]
path = "src/lib.rs"

[[bin]]
name = "partialzip"
path = "src/bin/partialzip.rs"
required-features = ["cmdline"]

[[bench]]
harness = false
name = "pz_benchmark"

[dependencies]
anyhow = {version = "1.0.68", optional = true}
bytesize = "1.1.0"
clap = {version = "4.1.1", optional = true}
conv = "0.3.3"
curl = "0.4.44"
env_logger = {version = "0.10.0", optional = true}
indicatif = {version = "0.17.3", optional = true}
log = "0.4.17"
num-traits = "0.2.15"
thiserror = "1.0.38"
url = "2.3.1"
zip = "0.6.3"

[dev-dependencies]
actix-files = "0.6.2"
actix-web = {version = "4.2.1", default-features = false, features = []}
anyhow = "1.0.68"
assert_cmd = "2.0.8"
criterion = "0.4.0"
predicates = "2.1.5"
tempfile = "3.3.0"
tokio = {version = "1.24.1", features = ["macros", "rt-multi-thread"]}
