[package]
authors = ["marcograss"]
categories = ["command-line-utilities", "compression", "encoding", "parsing", "parser-implementations"]
default-run = "partialzip"
description = "Download single files from online zip archives"
documentation = "https://docs.rs/partialzip"
edition = "2021"
exclude = ["/testdata"]
homepage = "https://github.com/marcograss/partialzip"
keywords = ["network", "utility", "io", "tool", "library"]
license = "MPL-2.0"
name = "partialzip"
readme = "README.md"
repository = "https://github.com/marcograss/partialzip"
rust-version = "1.60.0"
version = "1.2.6"

[dependencies]
anyhow = "1.0.66"
bytesize = "1.1.0"
clap = "4.0.18"
conv = "0.3.3"
curl = "0.4.44"
num-traits = "0.2.15"
thiserror = "1.0.37"
url = "2.3.1"
zip = "0.6.3"

[dev-dependencies]
actix-files = "0.6.2"
actix-web = {version = "4.2.1", default-features = false, features = []}
assert_cmd = "2.0.5"
predicates = "2.1.1"
tempfile = "3.3.0"
tokio = {version = "1.21.2", features = ["macros", "rt-multi-thread"]}
