name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: taiki-e/install-action@cargo-hack
    - name: Build
      run: cargo build --verbose
    - name: Cargo hack
      run: cargo clean && cargo hack --each-feature test
    - name: Run tests
      run: cargo test --verbose
    - name: Clippy Pedantic
      run: cargo clippy -- -D clippy::pedantic
